### PR TITLE
use node.js style require

### PR DESCRIPTION
**Pull request by dominictarr**
This makes verlet-js publishable on npm,

npm makes managing modules way way easier,
and works well on the client if you bundle modules with [browserify](https://github.com/substack/node-browserify)

I also have a branch that I've ported to use [vec2](https://npm.im/vec2),
I wanted to write a spatial hash lib, to use to efficiently create and destroy
constraints to nearby nodes, but I wanted it to work with a generic,
community supported vector lib - because then it would be usable with other people's modules.

However, this pull request is just about getting verlet into npm!

### CODE REVIEW

**Comment by subprotocol** [comment]
This is great!  I am new to npm, how do I make changes and get them to show up in dist.js?  Could you add some simple workflow instructions to the bottom of README.md for node newbies like myself?

**Comment by dominictarr** [comment]
oh! sorry, I forgot I had been fiddling with stuff. put the gravity back.
to build dist.js you can just do `browserify ./lib/dist.js --debug > ./dist.js`. I've also added that command to the package.json so you can just type: `npm run build`

**Comment by subprotocol** [comment]
Thanks!  It's working great for me. Two small questions and then I'll merge this in-
- instead of sticking dist.js directly onto the projects root, could it be placed into a different folder?  ie- `browserify ./lib/dist.js --debug > js/verlet-1.0.0.js`.  Would doing something like this make sense?
- would it be possible to have `npm run build` also generate a minimized version of the file?  Something like js/verlet-1.0.0.min.js? (not required for this pull request, but I'm curious if it would be easy to put in)

**Comment by dominictarr** [comment]
Oh, very simple! 
Of course, we can just use a popular minification tool from npm...

https://github.com/dominictarr/verlet-js/commit/3a2f1a9d0ae1be1ee3007047b930618394ddf65d#L5R11

**Comment by subprotocol** [comment]
This is great! Can you also checkin the files under the js directory?  Aside from that this looks ready to go in to me.  Get that dir checked in and I'll merge ASAP.  Thank you!!

**Comment by dominictarr** [comment]
done.

**Comment by subprotocol** [comment]
Awesome, thank you Dominic!

**Pull request merged**
